apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-honeytail-deployment
  namespace: default
  annotations:
    kubernetes.io/change-cause: "{ARG:CHANGE_CAUSE}"
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: postgres-honeytail
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-honeytail
    spec:
      containers:
        - image: "gcr.io/balmy-ground-195100/postgres-honeytail:{IMAGEID:postgres-honeytail}"
          name: postgres-honeytail-ctr
          # This pod is a 'Burstable' pod, ref:
          #  https://medium.com/google-cloud/quality-of-service-class-qos-in-kubernetes-bb76a89eb2c6
          resources:
            requests:
              memory: "128Mi"
              cpu: "1000m"
            limits:
              memory: "384Mi"
              cpu: "2000m"
          env:
            - name: DARK_CONFIG_RUNNING_IN_GKE
              value: "true"
            - name: GOOGLE_APPLICATION_CREDENTIALS_JSON
              valueFrom:
                secretKeyRef:
                  name: dark-static-assets
                  key: balmy-ground-195100-d9b0f3de3013.json
            - name: HONEYCOMB_WRITEKEY
              valueFrom:
                secretKeyRef:
                  name: honeycomb-account-credentials
                  key: api-key
            - name: SUBSCRIPTION_NAME
              value: postgres-logs-dark-west-honeycomb
            - name: PROJECT_ID
              value: balmy-ground-195100
