kind: Service
apiVersion: v1
metadata:
  name: darklang-nodeport
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app: bwd-app
  ports:
    - name: darklang-nodeport-port
      protocol: TCP
      port: 80
      targetPort: http-proxy-port
