honeycomb:
  existingSecret: honeycomb-account-credentials
  apiHost: https://api.honeycomb.io/

metrics:
  clusterName: darkcluster1
  dataset: kubernetes-metrics
  enabled: true
  metricGroups:
    - node
    - pod
    - container

watchers:

  # -------------
  # Main apps
  # -------------

  ## Garbage collector
  - labelSelector: "app=garbagecollector"
    containerName: garbagecollector-ctr
    dataset: kubernetes-garbagecollector
    parser: json
    processors:
      - sample:
          type: static
          rate: 10 # 1/10 sample rate

  ## Scheduler
  - labelSelector: "app=scheduler-worker"
    containerName: scheduler-ctr
    dataset: kubernetes-scheduler
    parser: json

  ## Editor
  - labelSelector: "app=editor-app"
    containerName: bwd-ctr
    dataset: kubernetes-bwd-ocaml
    parser: json
    processors:
      - request_shape:
          field: handler_name
          patterns:
            - /a/:canvas
            - /api/:canvas/save_test
            - /api/:canvas/rpc
            - /api/:canvas/add_op
            - /api/:canvas/initial_load
            - /api/:canvas/execute_function
            - /api/:canvas/get_trace_data
            - /api/:canvas/get_unlocked_dbs
            - /api/:canvas/get_worker_stats
            - /api/:canvas/get_db_stats
            - /api/:canvas/delete_404
            - /api/:canvas/static_assets
            - /canvas/:canvas/events/:event # stroller - not currently routed through nginx

  ## qw
  - labelSelector: "app=qw-worker"
    containerName: qw-ctr
    dataset: kubernetes-bwd-ocaml
    parser: json



  # -------------
  # Sidecars
  # -------------

  ## Stroller
  - labelSelector: "app in (editor-app, qw-worker)"
    containerName: stroller
    dataset: kubernetes-stroller
    processors:
      - sample:
          type: static
          rate: 100 # 1/100 sample rate
    parser: json

  ## Legacy-ctr: the apiserver itself uses opentelemetry to write directly, but the
  ## legacyserver still uses json logs like the rest of ocaml containers
  - labelSelector: "app in (apiserver-app, bwdserver-app, queueworker-app)"
    namespace: darklang
    containerName: legacy-ctr
    dataset: kubernetes-bwd-ocaml
    parser: json

  ## cloudsql-proxy (darklang namespace): does json logs
  - labelSelector: "app in (apiserver-app, bwdserver-app, queueworker-app, exechost-app)"
    namespace: darklang
    containerName: cloudsql-proxy
    dataset: cloudsql-proxy
    parser: json

  ## cloudsql-proxy (default namespace)
  - labelSelector: "app in (editor-app, cronchecker, scheduler-worker, qw-worker, garbagecollector)"
    containerName: cloudsql-proxy
    dataset: cloudsql-proxy
    parser: json

  ## nginx sidecar (for editor, which only does static assets traffic)
  - labelSelector: "app=editor-app"
    containerName: http-proxy
    dataset: kubernetes-bwd-nginx
    parser:
      name: nginx
      dataset: kubernetes-bwd-nginx
      options:
        config_file: /etc/nginx/conf.d/nginx.conf
        log_format: '$remote_addr - $remote_user [$time_local] $host "$request" $status $bytes_sent $body_bytes_sent $request_time "$http_referer" "$http_user_agent" $request_length "$http_authorization" "$http_x_forwarded_proto" "$http_x_forwarded_for" $server_name "$upstream_http_x_darklang_execution_id" "$http_cookie" "$upstream_http_x_dark_username" "$http_x_darklang_client_version" "$upstream_http_x_darklang_server_version"'

  ## nginx sidecar (for apiserver)
  - labelSelector: "app=apiserver-app"
    namespace: darklang
    containerName: http-proxy
    dataset: kubernetes-bwd-nginx
    parser:
      name: nginx
      dataset: kubernetes-bwd-nginx
      options:
        config_file: /etc/nginx/conf.d/nginx.conf
        log_format: '$remote_addr - $remote_user [$time_local] $host "$request" $status $bytes_sent $body_bytes_sent $request_time "$http_referer" "$http_user_agent" $request_length "$http_authorization" "$http_x_forwarded_proto" "$http_x_forwarded_for" $server_name "$upstream_http_x_darklang_execution_id" "$http_cookie" "$upstream_http_x_dark_username" "$http_x_darklang_client_version" "$upstream_http_x_darklang_server_version"'
    processors:
      - drop_field:
          field: http_authorization
      - drop_field:
          field: http_cookie
      - request_shape:
          field: request
          patterns:
            - /a/:canvas
            - /api/:canvas/add_op
            - /api/:canvas/all_traces
            - /api/:canvas/delete-secret
            - /api/:canvas/delete-toplevel-forever
            - /api/:canvas/delete_404
            - /api/:canvas/execute_function
            - /api/:canvas/get_404s
            - /api/:canvas/get_db_stats
            - /api/:canvas/get_trace_data
            - /api/:canvas/get_unlocked_dbs
            - /api/:canvas/get_worker_stats
            - /api/:canvas/initial_load
            - /api/:canvas/insert_secret
            - /api/:canvas/static_assets
            - /api/:canvas/trigger_handler
            - /api/:canvas/worker_schedule

  # -------------
  # ingress
  # -------------

  ## Nginx ingress controller for custom domains
  - labelSelector: "app.kubernetes.io/name=darkcustomdomain-nginx-ingress-controller"
    containerName: nginx-ingress-controller
    parser: nginx
    dataset: kubernetes-bwd-nginx
    processors:
      - request_shape:
        field: request



verbosity: info
# splitLogging directs trace, debug, info, and warn log levels to stdout
# rather than stderr.
splitLogging: false
