# If you are editing the configmap, you probably also want to delete the old
# honeycomb-agent pods so there will be new ones with the new config:
# `kubectl delete pod --selector k8s-app=honeycomb-agent`
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster-honeycomb
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: heapster
    spec:
      serviceAccountName: honeycomb-heapster
      containers:
        - name: heapster
          image: gcr.io/google_containers/heapster-amd64:v1.5.1
          imagePullPolicy: Always
          command:
            - /heapster
          args:
            - --source=kubernetes:https://kubernetes.default
            - --sink=honeycomb:?dataset=kubernetes-resource-metrics
          env:
            - name: HONEYCOMB_WRITEKEY
              valueFrom:
                secretKeyRef:
                  key: key
                  name: honeycomb-writekey
        - name: eventer
          image: gcr.io/google_containers/heapster-amd64:v1.5.1
          imagePullPolicy: Always
          command:
            - /eventer
          args:
            - --source=kubernetes:https://kubernetes.default
            - --sink=honeycomb:?dataset=kubernetes-cluster-events
          env:
            - name: HONEYCOMB_WRITEKEY
              valueFrom:
                secretKeyRef:
                  key: key
                  name: honeycomb-writekey
---
kind: ClusterRoleBinding
# kubernetes versions before 1.8.0 should use rbac.authorization.k8s.io/v1beta1
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: honeycomb-heapster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:heapster
subjects:
  - kind: ServiceAccount
    name: honeycomb-heapster
    namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: honeycomb-heapster
  namespace: kube-system
...
